LIKE_WEIGHT = 5.0        
DISLIKE_WEIGHT = -5.0     
STAR_RATING_WEIGHTS = {  
    0.5: -5.0,
    1.0: -3.5,
    1.5: -2.0,
    2.0: -1.0,
    2.5: 0.0,
    3.0: 0.5,
    3.5: 1.0,
    4.0: 2.0,
    4.5: 4.0,
    5.0: 5.0
}

# POSITIVE_FEEDBACK_THRESHOLD = 0.1 
# QA_WEIGHT = 0.5  
CONTENT_FEEDBACK_WEIGHT = 0.5  
# MIN_FEEDBACK_FOR_PERSONA_DETERMINATION = 1  
# MIN_POSITIVE_RATINGS_FOR_GROWTH = 1  
# PENALTY_FOR_NO_PERSONA_MATCH = -1.5  

# PERSONA_SIMILARITY_THRESHOLD = 0.5 
# CONTENT_SIMILARITY_THRESHOLD = 0.3 
CF_SIMILARITY_THRESHOLD = 0.1 


# TOP_N_CONTENTS_FOR_POPULAR_PER_PERSONA = 100 
RECOMMENDATION_COUNT = 10
SIMILAR_USERS_COUNT = 50
SIMILAR_CONTENTS_COUNT = 50

# MIN_VOTE_COUNT_FOR_POPULARITY = 1

# QA_INITIAL_RECOMMENDATION_THRESHOLD = 0.5 


MAX_EXPECTED_PERSONA_SCORE = 100.0 
MIN_PERSONA_SCORE = 0.1                         
# BABY_PERSONA_THRESHOLD = 10.0 

LOG_LEVEL = "INFO"
